### ISSUE TITLE
Important Question

### ISSUE THREAD

**Issue by bootslag** [nathanhi/android_kernel_lenovo_msm8909#1]
I'd like to know the exact version of this kernel version. I'm planning to build a custom kernel tree as my device's kernel is 3.10 and Oreo needs atleast 3.18. Another question - Will this kernel tree be compatible with any sort of device running msm8909? 

thanks in advance!

**Comment by nathanhi** [comment]
I'd love to help you here, but this kernel is just another unmodified source drop from Lenovo for achilles-type devices (TB2 X30), which unfortunately is v3.10, as indicated by the Makefile:

https://github.com/nathanhi/android_kernel_lenovo_msm8909/blob/master/Makefile

I've made some changes that I didn't push to make it at least buildable with GCC 6, but I guess that won't help you, if 3.10 isn't working for Oreo.

Have you checked the official MSM sources for Oreo support? At least there is an 8.1 tag, but that seems to use 3.10 as well, maybe the required changes have been backported to that kernel - it's worth a try.

https://android.googlesource.com/kernel/msm/

**Comment by bootslag** [comment]
Hello there o/

I'm trying to build LineageOS 15.1 (Which is based on Android 8.1 Oreo
android-8.1.0_r20
I think?) for my Lenovo Yoga tablet 3 8 (Lenovo YT3-850M) as Lenovo's
upgrade matrix makes Android 6.0.1 the latest version my tablet can have.
I'm relatively new but enthusiastic about custom ROM development. I didn't
know about Oreo's kernel requirements ( <goog_566032537>
https://www.xda-developers.com/google-mandating-linux-kernel-versions-android-oreo/)
until I got a warning message mentioning "*Deprecated Kernel Header Path
Dependencies"* while I was trying to build my ROM.

I have the open source code for my device (obtained from
https://pcsupport.lenovo.com/uu/en/products/tablets/yoga-series/yoga-tab-3-8/downloads/DS105446)
and I'm thinking about replacing the contents of the kernel folder
with  *android
/ kernel / common / android-3.18* (
https://android.googlesource.com/kernel/common/+/android-3.18). What would
happen then? Or should I merge this:
https://android.googlesource.com/kernel/msm/+/android-8.1.0_r0.20 ?

As you can see sir I'm not a professional and I'm just scratching the
surface of custom ROM development, hence why I would greatly appreciate
some guidance on how I should proceed. I have attached my device's
build.prop and my kernel's defconfig files for you to look at. I would
greatly appreciate guidance on how I should be proceeding.

Regards.

**Comment by bootslag** [comment]
Replacing my original contents of the kernel folder with the ones from
Googlesource.

**Comment by bootslag** [comment]
Do you have any work contact information such as email you'd wish to provide so I can get in touch with you? I have a few queries that's making me stuck in developing a ROM.
